### ISSUE TITLE
Add browsing for src/dst directory into main GUI window

### ISSUE THREAD

**Issue by Kreateer** [Kreateer/automatic-file-sorter#10]
# Goal

- Remove popup windows and add them as static GUI element to browse Source/Destination directories.

# Details

- Instead of having the program show popups to browse for Source and Destination directories, it would be more convenient to have the popups re-added as static GUI elements to the main window.

**Comment by arjunKay** [comment]
@Kreateer I can take this up 😊

**Comment by Kreateer** [comment]
@arjunKay Sure thing! 😊
Make sure you update your forked repo before you make another PR as I edited some files just now 😁

**Comment by Kreateer** [comment]
@arjunKay Are you still working on this? 😁❓

**Comment by arjunKay** [comment]
@Kreateer Yes, it's almost done. I couldn't test/push the changes because I was caught up in work. Will try to wrap this up today.
