### ISSUE TITLE
Add more file types 

### ISSUE THREAD

**Issue by Kreateer** [Kreateer/automatic-file-sorter#12]
# Goal

- Add more (common) file types for the program to recognize.

# Details

- The program needs to recognize more (common) file types to move or copy by adding them to the appropriate list
- File types like .xlsx (Excel), .pptx (PowerPoint) and more that are commonly used and any other file types anyone thinks would be good to add

**NOTE:** This Issue will remain Open and accept any number of contributions until decided otherwise**

**Comment by saptarsi96** [comment]
@Kreateer Please add me as a contributor to your Readme.md

**Comment by Kreateer** [comment]
@saptarsi96 Of course 😄 Any and all contributions are valued ❤️

**Comment by wang-joseph** [comment]
Can we also add other file types and lists (eg. media files, etc)? I've looked at the code and I have an idea of where to add code to make these lists functional as well.

**Comment by Kreateer** [comment]
@EmeraldEntities Of course, you're welcome to add those in! 😄 
If you've read the [Contributing Guidelines](https://github.com/Kreateer/automatic-file-sorter/blob/master/CONTRIBUTING.md), please ignore the part where it says to wait before you're assigned as **this particular issue** is Open until I decide otherwise, so just keep those PRs coming 😁

**Comment by wang-joseph** [comment]
Awesome, I'll get some other file types in then! 😄

**Comment by polynoman** [comment]
@Kreateer would it make sense to add file types of code files? ".py"  ".c"  ".cpp" etc..

**Comment by Kreateer** [comment]
@polynoman Sure! Feel free to add any file types you feel would be useful for the program to know! 😄
The more file types it knows, the better! 😁

**Comment by polynoman** [comment]
#22 is what i have added now.
