### ISSUE TITLE
Pressing cancel on source/dest folder selection does not work. <BUG>

### ISSUE THREAD

**Issue by wang-joseph** [Kreateer/automatic-file-sorter#14]
**Please describe the issue in detail here.**
Pressing the cancel button on either the source or destination folders does not exit the program as expected, but instead continues as if the user had provided a valid folder. Upon clicking 'OK' on the main options menu, however, the program will crash with the following stack trace (line numbers may be slightly off):
```
Traceback (most recent call last):
  File "fmain.py", line 245, in <module>
    main_gui.main_window()
  File "fmain.py", line 68, in main_window
    run_fmover.filemover(values['OPERATION'], None, values['OVERWRITE'])
  File "fmain.py", line 143, in filemover
    num_files = len(os.listdir(get_path('src')))
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'None'
```

**Describe the solution you'd like to implement**
Simply checking if the user had pressed cancel at that menu and acting accordingly would solve this issue, but I've never used PySimpleGUI before and don't know how they implement everything.

**Comment by Kreateer** [comment]
@EmeraldEntities Nice find! 😄 If you'd like to try fix it, you can refer to the detailed [PySimpleGUI documentation](https://pysimplegui.readthedocs.io/en/latest/) 📝

**Comment by wang-joseph** [comment]
@Kreateer haha perhaps I'll try later on tonight if no one else who stumbles on this wants to do it 😄

**Comment by Kreateer** [comment]
@EmeraldEntities I'll assign myself then and get to fixing it. Likely making a PR tomorrow tho 😁

**Comment by wang-joseph** [comment]
@Kreateer sounds good to me, maybe I'll pick some pysimplegui later and contribute more on this haha

**Comment by Kreateer** [comment]
@EmeraldEntities Awesome! 😄 👍 
PySimpleGUI is honestly not difficult at all. if you're interested in it, it'll maybe take you a day or two at most to figure things out. You're welcome to use this program to experiment with it 😁
