### ISSUE TITLE
Create a GUI option that asks user if and how they wish to sort files

### ISSUE THREAD

**Issue by Kreateer** [Kreateer/automatic-file-sorter#3]
# Goal

- Asks user if they want to sort the files by specific criteria (name, date, size etc.).

# Details

- When the program launches, the GUI window should have an option that asks the user for source/destination folder and how or if they wish to sort the files based on one or several additional criteria (name, date, size, etc.).
- This issue is in tandem with issue #1

**Comment by pushp1997** [comment]
Hey @Kreateer if you havent already started working on this,  I would like to take it. Thanks! 😊

**Comment by Kreateer** [comment]
@pushp1997 I'm more focusing on Issue #1 right now, so you're welcome to work on this issue. 😁
If it helps, you can refer to the experimental `sortingfunction` branch to see some changes I made. 😊

**Comment by pushp1997** [comment]
Sure, thanks! 😊
