### ISSUE TITLE
Allow the user to choose whether to copy or move files to destination

### ISSUE THREAD

**Issue by Kreateer** [Kreateer/automatic-file-sorter#4]
# Goal

- Program allows the user to choose whether to copy or move files from source to destination.

# Details

- The program should give the user a choice between copying or moving the files from source to destination. Preferably, this would be a GUI dropdown or checkbox option when the program is run, either as a popup window or part of a main GUI.
- The GUI has to be created using [PySimpleGUI](https://pysimplegui.readthedocs.io/en/latest/)

**Comment by pushp1997** [comment]
Hi @Kreateer I would like to work on this issue, can you assign it to me, please?

**Comment by Kreateer** [comment]
@pushp1997 Hi! Sure, go ahead! ^^

**Comment by Kreateer** [comment]
@pushp1997 in the latest commit, I fixed an important issue that I somehow missed until now (*oops* 😅 ) and re-organized the main script, so make sure you have the new version of the file before continuing on with the issue 😊

**Comment by pushp1997** [comment]
Sure, got it! @Kreateer

**Comment by pushp1997** [comment]
One more thing, shoould it be a popup or should I add it to the main windows above the filetyepe dropdown?

**Comment by Kreateer** [comment]
@pushp1997 well, until now the basic popup worked fine for it, but I have plans to replace the popups with options in the main window, so any updates to the GUI should go into the main layout 😄

**Comment by pushp1997** [comment]
Hey @Kreateer, please review the PR #7 that I have raised for the same and let me know if further changes are required. Thank you 😊

**Comment by Kreateer** [comment]
@pushp1997 Got it, will have a look in a bit! 😃
