### ISSUE TITLE
Create option to overwrite existing files

### ISSUE THREAD

**Issue by Kreateer** [Kreateer/automatic-file-sorter#9]
# Goal

- Allow the user to choose whether to overwrite existing files or not.

# Details

- When the user enables this option, any existing files in the destination directory should be overwritten (deleted and then copied or moved again) or replaced by the newer version of the file.
- When disabled, all existing files are not overwritten and instead another copy is made for each file.
- This function depends on user interaction (when user clicks button/ticks checkbox etc.), so a GUI option must be made for it using [PySimpleGUI](https://pysimplegui.readthedocs.io/en/latest/)

**Comment by arjunKay** [comment]
Hi @Kreateer, I would like to take up this issue. Could you please assign it to me?

**Comment by Kreateer** [comment]
@arjunKay Sure! Thank you! 😄
